const fs = require('fs');

const extraEn = {
  fullSyllabusTest: "Full Syllabus Test",
  chapterTest: "Chapter {id} Test",
  elapsed: "Elapsed",
  finishTest: "Finish Test",
  searchQuestions: "Search questions...",
  flag: "Flag",
  previous: "Previous",
  next: "Next",
  explanation: "Explanation",
  testConsole: "Test Console",
  answered: "Answered",
  notAnswered: "Not Answered",
  flaggedForReview: "Flagged for Review",
  correctAnswer: "Correct Answer",
  incorrectAnswer: "Incorrect Answer",
  outstandingTitle: "Outstanding! Elite Performance!",
  outstandingDesc: "You have excellent knowledge of these concepts.",
  greatTitle: "Great Effort! Well Done!",
  greatDesc: "Good performance, but there is still room for improvement.",
  needsStudyTitle: "Needs More Study!",
  needsStudyDesc: "Keep practicing to improve your score.",
  overallScore: "Overall",
  testScorecard: "TEST SCORECARD",
  scorecardDesc: "You have successfully completed the mock test. Your complete results are shown below. You can review exact explanations for each question.",
  retakeTest: "Retake Test",
  backToDashboard: "Back to Dashboard",
  unlockAllNow: "Unlock All Now (Only ₹{amount})",
  totalQs: "Total Qs",
  correct: "Correct",
  incorrect: "Incorrect",
  skippedLabel: "Skipped",
  timeTaken: "Time Taken",
  skippedValue: "Skipped",
  correctValue: "Correct",
  incorrectValue: "Incorrect",
  reviewPanel: "Review Panel"
};

const extraMr = {
  fullSyllabusTest: "पूर्ण अभ्यासक्रम चाचणी",
  chapterTest: "विषय {id} चाचणी",
  elapsed: "गेलेला वेळ",
  finishTest: "चाचणी पूर्ण करा",
  searchQuestions: "प्रश्न शोधा...",
  flag: "पुनरावलोकन",
  previous: "मागील",
  next: "पुढील",
  explanation: "स्पष्टीकरण",
  testConsole: "चाचणी नेव्हिगेशन",
  answered: "उत्तर दिलेले",
  notAnswered: "उत्तर न दिलेले",
  flaggedForReview: "पुनरावलोकनासाठी चिन्हांकित",
  correctAnswer: "बरोबर उत्तर",
  incorrectAnswer: "चूक उत्तर",
  outstandingTitle: "उत्कृष्ट! अप्रतिम कामगिरी!",
  outstandingDesc: "तुम्हाला या संकल्पनांचे उत्तम ज्ञान आहे.",
  greatTitle: "चांगला प्रयत्न! छान!",
  greatDesc: "चांगली कामगिरी, पण अजून सुधारणेला वाव आहे.",
  needsStudyTitle: "अधिक अभ्यासाची गरज!",
  needsStudyDesc: "तुमचे गुण वाढवण्यासाठी सराव करत राहा.",
  overallScore: "एकूण गुण",
  testScorecard: "चाचणी निकाल",
  scorecardDesc: "तुम्ही यशस्वीरित्या चाचणी पूर्ण केली आहे. तुमचे निकाल खालीलप्रमाणे आहेत. तुम्ही सर्व प्रश्नांची अचूक उत्तरे आणि स्पष्टीकरणे खाली पाहू शकता.",
  retakeTest: "पुन्हा परीक्षा द्या",
  backToDashboard: "डॅशबोर्डवर जा",
  unlockAllNow: "आता अनलॉक करा (फक्त ₹{amount})",
  totalQs: "एकूण प्रश्न",
  correct: "बरोबर",
  incorrect: "चुकीचे",
  skippedLabel: "सोडवून दिले",
  timeTaken: "घेतलेला वेळ",
  skippedValue: "सोडून दिला (Skipped)",
  correctValue: "बरोबर (Correct)",
  incorrectValue: "चुकीचे (Incorrect)",
  reviewPanel: "सर्व प्रश्न तपासा"
};

const extraHi = {
  fullSyllabusTest: "पूर्ण पाठ्यक्रम टेस्ट",
  chapterTest: "अध्याय {id} टेस्ट",
  elapsed: "समय",
  finishTest: "टेस्ट समाप्त करें",
  searchQuestions: "प्रश्न खोजें...",
  flag: "समीक्षा के लिए चिह्नित करें",
  previous: "पिछला",
  next: "अगला",
  explanation: "व्याख्या",
  testConsole: "टेस्ट नेविगेशन",
  answered: "उत्तर दिया गया",
  notAnswered: "उत्तर नहीं दिया",
  flaggedForReview: "समीक्षा के लिए चिह्नित",
  correctAnswer: "सही उत्तर",
  incorrectAnswer: "गलत उत्तर",
  outstandingTitle: "उत्कृष्ट! बेहतरीन प्रदर्शन!",
  outstandingDesc: "आपको इन अवधारणाओं का उत्कृष्ट ज्ञान है।",
  greatTitle: "अच्छा प्रयास! बहुत बढ़िया!",
  greatDesc: "अच्छा प्रदर्शन, लेकिन अभी भी सुधार की गुंजाइश है।",
  needsStudyTitle: "अधिक अध्ययन की आवश्यकता!",
  needsStudyDesc: "अपना स्कोर सुधारने के लिए अभ्यास करते रहें।",
  overallScore: "कुल अंक",
  testScorecard: "टेस्ट स्कोरकार्ड",
  scorecardDesc: "आपने सफलतापूर्वक मॉक टेस्ट पूरा कर लिया है। आपके परिणाम नीचे दिखाए गए हैं।",
  retakeTest: "फिर से टेस्ट दें",
  backToDashboard: "डैशबोर्ड पर जाएं",
  unlockAllNow: "अभी अनलॉक करें (केवल ₹{amount})",
  totalQs: "कुल प्रश्न",
  correct: "सही",
  incorrect: "गलत",
  skippedLabel: "छोड़ दिया",
  timeTaken: "लिया गया समय",
  skippedValue: "छोड़ दिया (Skipped)",
  correctValue: "सही (Correct)",
  incorrectValue: "गलत (Incorrect)",
  reviewPanel: "समीक्षा पैनल"
};

const extraKn = {
  fullSyllabusTest: "ಪೂರ್ಣ ಪಠ್ಯಕ್ರಮ ಪರೀಕ್ಷೆ",
  chapterTest: "ಅಧ್ಯಾಯ {id} ಪರೀಕ್ಷೆ",
  elapsed: "ಸಮಯ",
  finishTest: "ಪರೀಕ್ಷೆ ಮುಗಿಸಿ",
  searchQuestions: "ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...",
  flag: "ಫ್ಲ್ಯಾಗ್",
  previous: "ಹಿಂದಿನ",
  next: "ಮುಂದಿನ",
  explanation: "ವಿವರಣೆ",
  testConsole: "ಪರೀಕ್ಷಾ ಕನ್ಸೋಲ್",
  answered: "ಉತ್ತರಿಸಲಾಗಿದೆ",
  notAnswered: "ಉತ್ತರಿಸಿಲ್ಲ",
  flaggedForReview: "ಪರಿಶೀಲನೆಗಾಗಿ ಫ್ಲ್ಯಾಗ್ ಮಾಡಲಾಗಿದೆ",
  correctAnswer: "ಸರಿಯಾದ ಉತ್ತರ",
  incorrectAnswer: "ತಪ್ಪು ಉತ್ತರ",
  outstandingTitle: "ಅತ್ಯುತ್ತಮ ಪ್ರದರ್ಶನ!",
  outstandingDesc: "ಈ ಪರಿಕಲ್ಪನೆಗಳ ಬಗ್ಗೆ ನಿಮಗೆ ಉತ್ತಮ ಜ್ಞಾನವಿದೆ.",
  greatTitle: "ಉತ್ತಮ ಪ್ರಯತ್ನ!",
  greatDesc: "ಉತ್ತಮ ಪ್ರದರ್ಶನ, ಆದರೆ ಇನ್ನೂ ಸುಧಾರಣೆಗೆ ಅವಕಾಶವಿದೆ.",
  needsStudyTitle: "ಹೆಚ್ಚಿನ ಅಧ್ಯಯನದ ಅಗತ್ಯವಿದೆ!",
  needsStudyDesc: "ಅಂಕಗಳನ್ನು ಸುಧಾರಿಸಲು ಅಭ್ಯಾಸವನ್ನು ಮುಂದುವರಿಸಿ.",
  overallScore: "ಒಟ್ಟಾರೆ",
  testScorecard: "ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶ",
  scorecardDesc: "ನೀವು ಪರೀಕ್ಷೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿದ್ದೀರಿ.",
  retakeTest: "ಮತ್ತೆ ಪರೀಕ್ಷೆ ಬರೆಯಿರಿ",
  backToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
  unlockAllNow: "ಈಗ ಅನ್ಲಾಕ್ ಮಾಡಿ (ಕೇವಲ ₹{amount})",
  totalQs: "ಒಟ್ಟು ಪ್ರಶ್ನೆಗಳು",
  correct: "ಸರಿ",
  incorrect: "ತಪ್ಪು",
  skippedLabel: "ಬಿಡಲಾಗಿದೆ",
  timeTaken: "ತೆಗೆದುಕೊಂಡ ಸಮಯ",
  skippedValue: "ಬಿಡಲಾಗಿದೆ",
  correctValue: "ಸರಿ",
  incorrectValue: "ತಪ್ಪು",
  reviewPanel: "ವಿಮರ್ಶೆ ಪ್ಯಾನಲ್"
};

const extraTe = {
  fullSyllabusTest: "పూర్తి సిలబస్ పరీక్ష",
  chapterTest: "అధ్యాయం {id} పరీక్ష",
  elapsed: "సమయం",
  finishTest: "పరీక్ష ముగించండి",
  searchQuestions: "ప్రశ్నలను శోధించండి...",
  flag: "ఫ్లాగ్ చేయండి",
  previous: "మునుపటి",
  next: "తర్వాత",
  explanation: "వివరణ",
  testConsole: "పరీక్ష కన్సోల్",
  answered: "సమాధానం ఇచ్చారు",
  notAnswered: "సమాధానం ఇవ్వలేదు",
  flaggedForReview: "సమీక్ష కోసం ఫ్లాగ్ చేయబడింది",
  correctAnswer: "సరైన సమాధానం",
  incorrectAnswer: "తప్పు సమాధానం",
  outstandingTitle: "అద్భుతమైన ప్రదర్శన!",
  outstandingDesc: "మీకు ఈ భావనలపై మంచి అవగాహన ఉంది.",
  greatTitle: "మంచి ప్రయత్నం!",
  greatDesc: "మంచి ప్రదర్శన, కానీ ఇంకా మెరుగుపడాలి.",
  needsStudyTitle: "మరింత అధ్యయనం అవసరం!",
  needsStudyDesc: "ప్రాక్టీస్ చేస్తూ ఉండండి.",
  overallScore: "మొత్తం స్కోర్",
  testScorecard: "పరీక్ష ఫలితాలు",
  scorecardDesc: "మీరు పరీక్షను విజయవంతంగా పూర్తి చేసారు.",
  retakeTest: "మళ్లీ పరీక్ష రాయండి",
  backToDashboard: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
  unlockAllNow: "ఇప్పుడే అన్‌లాక్ చేయండి (₹{amount} మాత్రమే)",
  totalQs: "మొత్తం ప్రశ్నలు",
  correct: "సరైనవి",
  incorrect: "తప్పు",
  skippedLabel: "వదిలేశారు",
  timeTaken: "తీసుకున్న సమయం",
  skippedValue: "వదిలేశారు",
  correctValue: "సరైనది",
  incorrectValue: "తప్పు",
  reviewPanel: "సమీక్ష ప్యానెల్"
};

const extraTa = {
  fullSyllabusTest: "முழு பாடத்திட்ட தேர்வு",
  chapterTest: "பாடம் {id} தேர்வு",
  elapsed: "நேரம்",
  finishTest: "தேர்வை முடிக்கவும்",
  searchQuestions: "கேள்விகளைத் தேடுக...",
  flag: "கொடியிடு",
  previous: "முந்தைய",
  next: "அடுத்த",
  explanation: "விளக்கம்",
  testConsole: "தேர்வு வழிகாட்டி",
  answered: "பதிலளிக்கப்பட்டது",
  notAnswered: "பதிலளிக்கப்படவில்லை",
  flaggedForReview: "மதிப்பாய்வுக்காக குறிக்கப்பட்டது",
  correctAnswer: "சரியான பதில்",
  incorrectAnswer: "தவறான பதில்",
  outstandingTitle: "சிறப்பான செயல்பாடு!",
  outstandingDesc: "உங்களுக்கு நல்ல அறிவு உள்ளது.",
  greatTitle: "நல்ல முயற்சி!",
  greatDesc: "நல்ல செயல்பாடு, இன்னும் முன்னேறலாம்.",
  needsStudyTitle: "மேலும் படிக்க வேண்டும்!",
  needsStudyDesc: "தொடர்ந்து பயிற்சி செய்யுங்கள்.",
  overallScore: "மொத்த மதிப்பெண்",
  testScorecard: "தேர்வு முடிவுகள்",
  scorecardDesc: "நீங்கள் தேர்வை வெற்றிகரமாக முடித்துள்ளீர்கள்.",
  retakeTest: "மீண்டும் தேர்வு எழுதுக",
  backToDashboard: "முகப்புக்குத் திரும்பு",
  unlockAllNow: "இப்போதே திறக்கவும் (₹{amount} மட்டும்)",
  totalQs: "மொத்த கேள்விகள்",
  correct: "சரி",
  incorrect: "தவறு",
  skippedLabel: "தவிர்க்கப்பட்டது",
  timeTaken: "எடுத்துக்கொண்ட நேரம்",
  skippedValue: "தவிர்க்கப்பட்டது",
  correctValue: "சரி",
  incorrectValue: "தவறு",
  reviewPanel: "மதிப்பாய்வு குழு"
};

const extraGu = {
  fullSyllabusTest: "સંપૂર્ણ અભ્યાસક્રમ પરીક્ષણ",
  chapterTest: "પ્રકરણ {id} પરીક્ષણ",
  elapsed: "સમય",
  finishTest: "પરીક્ષણ સમાપ્ત કરો",
  searchQuestions: "પ્રશ્નો શોધો...",
  flag: "ફ્લેગ કરો",
  previous: "અગાઉનું",
  next: "આગળ",
  explanation: "સમજૂતી",
  testConsole: "પરીક્ષણ કન્સોલ",
  answered: "જવાબ આપેલ",
  notAnswered: "જવાબ આપેલ નથી",
  flaggedForReview: "સમીક્ષા માટે ફ્લેગ કરેલ",
  correctAnswer: "સાચો જવાબ",
  incorrectAnswer: "ખોટો જવાબ",
  outstandingTitle: "ઉત્કૃષ્ટ પ્રદર્શન!",
  outstandingDesc: "તમને આ ખ્યાલોનું સારું જ્ઞાન છે.",
  greatTitle: "સારો પ્રયાસ!",
  greatDesc: "સારું પ્રદર્શન, પરંતુ હજુ સુધારાની જરૂર છે.",
  needsStudyTitle: "વધુ અભ્યાસની જરૂર છે!",
  needsStudyDesc: "પ્રેક્ટિસ કરતા રહો.",
  overallScore: "કુલ ગુણ",
  testScorecard: "પરીક્ષણ પરિણામો",
  scorecardDesc: "તમે સફળતાપૂર્વક પરીક્ષણ પૂર્ણ કર્યું છે.",
  retakeTest: "ફરીથી પરીક્ષણ આપો",
  backToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
  unlockAllNow: "હમણાં અનલૉક કરો (ફક્ત ₹{amount})",
  totalQs: "કુલ પ્રશ્નો",
  correct: "સાચું",
  incorrect: "ખોટું",
  skippedLabel: "છોડી દીધેલ",
  timeTaken: "લીધેલો સમય",
  skippedValue: "છોડી દીધેલ",
  correctValue: "સાચું",
  incorrectValue: "ખોટું",
  reviewPanel: "સમીક્ષા પેનલ"
};

let content = fs.readFileSync('src/utils/i18n.ts', 'utf8');

function injectExtra(content, lang, extra) {
  const extraStr = Object.entries(extra).map(([k, v]) => `    ${k}: "${v}",`).join('\n');
  const regex = new RegExp(`(${lang}: \\{[\\s\\S]*?)(  \\},)`);
  return content.replace(regex, `$1${extraStr}\n$2`);
}

content = injectExtra(content, 'en', extraEn);
content = injectExtra(content, 'mr', extraMr);
content = injectExtra(content, 'hi', extraHi);
content = injectExtra(content, 'kn', extraKn);
content = injectExtra(content, 'te', extraTe);
content = injectExtra(content, 'ta', extraTa);
content = injectExtra(content, 'gu', extraGu);

fs.writeFileSync('src/utils/i18n.ts', content, 'utf8');
console.log("Updated i18n.ts with new keys for all 7 languages");
