import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'src/data/questions.ts');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Add Chapter 17 to CHAPTERS array
const newChapter = {
  id: 17,
  name: "SET 15 (Questions 441-470)",
  nameMarathi: "प्रश्नसंच १५ (४४१ ते ४७०)",
  description: "Steering geometry, Suspension, Braking systems, and Engine Performance.",
  descriptionMarathi: "स्टीअरिंग जॉमेट्री, सस्पेन्शन, ब्रेकिंग सिस्टिम्स आणि इंजिन परफॉर्मन्स.",
  icon: "BarChart3"
};

const chaptersEndIdx = content.indexOf('];\n\nexport const QUESTIONS');
if (chaptersEndIdx !== -1) {
    const chaptersPart = content.substring(0, chaptersEndIdx).trimEnd();
    const separator = chaptersPart.endsWith(',') ? '\n' : ',\n';
    content = chaptersPart + separator + '  ' + JSON.stringify(newChapter, null, 2) + '\n' + content.substring(chaptersEndIdx);
}

// 2. Prepare Set 15 Questions (IDs 441-470)
const set15Questions = [
  { id: 441, chapterId: 17, question: "Positive caster is defined as the tilt of the steering axis towards the—", questionMarathi: "पॉझिटिव्ह कास्टर (Positive caster) मध्ये स्टीअरिंग ॲक्सिस कोणत्या दिशेला झुकलेला असतो?", options: ["Rear of the vehicle", "Front of the vehicle", "Left of the vehicle", "Right of the vehicle"], optionsMarathi: ["गाडीच्या मागच्या बाजूस", "गाडीच्या पुढच्या बाजूस", "डावीकडे", "उजवीकडे"], answer: "A", explanation: "Positive caster means the top of the kingpin tilts towards the rear, which enhances directional stability.", explanationMarathi: "पॉझिटिव्ह कास्टरमध्ये स्टीअरिंग ॲक्सिस मागच्या बाजूला झुकलेला असतो, ज्यामुळे गाडी सरळ धावण्यासाठी मदत होते." },
  { id: 442, chapterId: 17, question: "Slip angle is the angle between—", questionMarathi: "स्लिप अँगल (Slip angle) म्हणजे काय?", options: ["Direction of motion of the wheel and centerline of the wheel", "True vertical line and centerline of the wheel", "Axis of the stub axle and the tie rod line", "None of the above"], optionsMarathi: ["चाकाच्या गतीची दिशा आणि चाकाची मध्यरेखा", "उभी रेष", "स्टब अ‍ॅक्सलची अक्षांश", "यापैकी नाही"], answer: "A", explanation: "Slip angle is the difference between the direction the wheel is pointing and the direction the wheel is actually traveling.", explanationMarathi: "चाक ज्या दिशेला तोंड करून आहे आणि ज्या दिशेला ते प्रत्यक्षात फिरत आहे, यामधील कोनाला स्लिप अँगल म्हणतात." },
  { id: 443, chapterId: 17, question: "The basic purpose of 'Toe-out on turns' is to ensure that—", questionMarathi: "'टो-आउट ऑन टर्न्स' (Toe-out on turns) चा उद्देश काय?", options: ["The inner wheel turns through a larger angle than the outer wheel", "The outer wheel turns through a larger angle than the inner wheel", "Both wheels remain parallel during turning operations", "Tire scuffing is maximum at the corners"], optionsMarathi: ["आतले चाक बाहेरच्या चाकापेक्षा जास्त वळते", "बाहेरचे चाक जास्त वळते", "दोन्ही चाके समांतर राहतात", "टायर घासणे"], answer: "A", explanation: "During a turn, the inner wheel follows a smaller radius than the outer wheel, so it must turn at a sharper angle to prevent tire scrub.", explanationMarathi: "वळण घेताना आतल्या चाकाला कमी अंतर कापायचे असते, म्हणून ते बाहेरच्या चाकापेक्षा जास्त वळणे आवश्यक असते." },
  { id: 444, chapterId: 17, question: "The component that connects the two track rods in a split track-rod steering system is the—", questionMarathi: "स्प्लिट ट्रॅक-रॉड स्टीअरिंग सिस्टीममध्ये दोन ट्रॅक रॉड्स कशाने जोडलेले असतात?", options: ["Relay lever kiva central link arm", "Pitman arm dropped linkage", "Steering column lower pinion", "Front suspension stabilizer beam"], optionsMarathi: ["रिले लिव्हर (Relay lever) किंवा सेंट्रल लिंक आर्म", "पिटमॅन आर्म", "स्टीअरिंग कॉलम", "स्टेबिलायझर बीम"], answer: "A", explanation: "The relay lever (or idler arm) allows the steering motion to be transferred across the width of the vehicle.", explanationMarathi: "रिले लिव्हर हे स्टीअरिंगची हालचाल एका बाजूकडून दुसऱ्या बाजूला ट्रान्सफर करते." },
  { id: 445, chapterId: 17, question: "Helper springs are generally provided in the leaf spring layouts of—", questionMarathi: "'हेल्पर स्प्रिंग' (Helper springs) कोठे वापरतात?", options: ["Heavy commercial trucks and buses", "Lightweight sports racing cars", "Modern luxury electric sedans", "Two-wheeler motor vehicles"], optionsMarathi: ["अवजड ट्रक आणि बसेस", "रेसिंग कार", "लक्झरी कार", "दुचाकी"], answer: "A", explanation: "Helper springs engage only when the vehicle is heavily loaded, preventing the main springs from bottoming out.", explanationMarathi: "जेव्हा गाडीवर जास्त वजन असते, तेव्हा मुख्य स्प्रिंगला आधार देण्यासाठी हेल्पर स्प्रिंग वापरतात." },
  { id: 446, chapterId: 17, question: "In a telescopic hydraulic shock absorber, the damping fluid resistance is created by forcing oil through—", questionMarathi: "शॉक अ‍ॅब्जॉर्बरमध्ये तेलाचा रोध (Damping) कसा निर्माण होतो?", options: ["Small calibrated orifices and valves inside the piston assembly", "The external radiator cooling core layout tubes", "The master cylinder brake line check valves", "The spring shackle bushing pin channels"], optionsMarathi: ["पिस्टनच्या आत असलेल्या लहान छिद्रांमधून तेल गेल्यामुळे", "रेडिएटरद्वारे", "ब्रेक लाईनद्वारे", "बुशिंग पिनद्वारे"], answer: "A", explanation: "Forcing oil through tiny, restrictive holes (orifices) slows down the piston movement, which absorbs the shock energy.", explanationMarathi: "जेव्हा शॉक अ‍ॅब्जॉर्बर दाबला जातो, तेव्हा तेल लहान छिद्रांमधून बाहेर पडते, या रोधामुळे गाडीच्या झटक्याची तीव्रता कमी होते." },
  { id: 447, chapterId: 17, question: "In a hydraulic braking setup, the residual pressure valve inside the master cylinder serves to—", questionMarathi: "मास्टर सिलेंडरमधील 'रेसिड्यूअल प्रेशर व्हॉल्व्ह'चे कार्य काय?", options: ["Maintain a slight positive pressure in lines to prevent air entry and cup collapse", "Dump excess pressure back to the fluid reservoir during heavy emergency application", "Boost the vacuum diaphragm force applied by the driver's foot pedal linkage", "Bleed out the system automatically whenever air bubble pockets are detected"], optionsMarathi: ["पाइपलाईनमध्ये हलका दाब राखून हवा जाण्यापासून रोखणे", "जास्तीचे तेल टाकीत पाठवणे", "बूस्ट वाढवणे", "हवा काढणे"], answer: "A", explanation: "Maintaining a slight pressure in the brake lines ensures the rubber cups in the wheel cylinders stay tight against the bore, preventing air leaks.", explanationMarathi: "ब्रेक लाईनमध्ये थोडा दाब राहिल्यामुळे सिलिंडरच्या रबर कप्सची पकड राहते आणि हवा आत शिरत नाही." },
  { id: 448, chapterId: 17, question: "The brake caliper assembly in an automobile disc brake system is securely mounted on the—", questionMarathi: "डिस्क ब्रेकचा 'कॅलिपर' कुठे बसवलेला असतो?", options: ["Steering knuckle or axle casing bracket", "Rotating brake disc rotor face surface", "Master cylinder reservoir push rod", "Front wheel rim outer structural flange"], optionsMarathi: ["स्टीअरिंग नकल किंवा अ‍ॅक्सल ब्रॅकेटवर", "डिस्कवर", "मास्टर सिलेंडरवर", "चाकावर"], answer: "A", explanation: "The caliper needs to be held stationary so it can clamp down on the rotating disc to provide braking friction.", explanationMarathi: "कॅलिपर हा अ‍ॅक्सलला घट्ट बसवलेला असतो, जेणेकरून तो डिस्कला पकडून चाक थांबवू शकेल." },
  { id: 449, chapterId: 17, question: "Dynamic wheel balancing is executed to correct the mass distribution of a wheel assembly and prevent—", questionMarathi: "'डायनॅमिक बॅलन्सिंग' कशासाठी करतात?", options: ["Side-to-side wheel wobble or shimmy vibrations at high cruising speeds", "Severe vertical hopping or pounding movements at extremely low crawling speeds", "Sudden locking up of the brake shoe lining during emergency stops", "Excessive body lean or roll when negotiating tight corners on a grade"], optionsMarathi: ["जास्त वेगाला होणारे चाकाचे थरथरणे (Shimmy) टाळण्यासाठी", "कमी वेगाला चाक उडणे टाळण्यासाठी", "ब्रेक जाम होणे टाळण्यासाठी", "गाडी झुकणे टाळण्यासाठी"], answer: "A", explanation: "Dynamic balance corrects for uneven weight across the wheel's width and circumference, which causes side-to-side (wobble) and vertical vibrations.", explanationMarathi: "चाक वेगाने फिरताना जर त्याचे वजन सर्व बाजूला समान नसेल, तर ते थरथरायला लागते. हे थांबवण्यासाठी डायनॅमिक बॅलन्सिंग आवश्यक असते." },
  { id: 450, chapterId: 17, question: "Over-inflation of an automobile tire causes the maximum wear to manifest at the—", questionMarathi: "टायरमध्ये जास्त हवा भरली तर टायरची झीज कोठे होते?", options: ["Center of the tread pattern perimeter", "Two outer edges or shoulders of the tread print", "Internal bead seat layout section of the rim", "Tire sidewall structural rubber layer zone"], optionsMarathi: ["टायरच्या मध्यभागी", "टायरच्या कडांना", "रिमवर", "बाजूच्या भिंतीवर"], answer: "A", explanation: "Excessive pressure makes the center of the tire bow outward, causing that area to touch the road more and wear down faster.", explanationMarathi: "जास्त हवेमुळे टायरचा मध्यवर्ती भाग फुगतो आणि जमिनीवर घासल्यामुळे फक्त तिथूनच तो लवकर झिजतो." },
  { id: 451, chapterId: 17, question: "The volumetric efficiency of an internal combustion engine indicates—", questionMarathi: "इंजिनची 'व्हॉल्युमेट्रिक कार्यक्षमता' म्हणजे काय?", options: ["The breathing capacity or the ratio of actual air mass drawn to theoretical volume mass", "The ratio of brake power output to indicated power output variables", "The precise velocity map of combustion gases leaving the exhaust ports", "The physical storage volume metric of the vehicle fuel tank setup"], optionsMarathi: ["इंजिनची श्वास घेण्याची क्षमता", "ब्रेक पॉवरचे प्रमाण", "धुराचा वेग", "टाकीची क्षमता"], answer: "A", explanation: "It measures how well the engine 'breathes'. Higher volumetric efficiency means more air enters the cylinders, allowing for more fuel burning and higher power.", explanationMarathi: "इंजिन सिलेंडरच्या क्षमतेपेक्षा किती जास्त हवा आत ओढू शकते, यालाच व्हॉल्युमेट्रिक कार्यक्षमता म्हणतात." },
  { id: 452, chapterId: 17, question: "The phenomenon of pre-ignition in a spark ignition petrol engine cycle occurs due to—", questionMarathi: "पेट्रोल इंजिनमध्ये 'प्री-इग्निशन' (Pre-ignition) का होते?", options: ["Pre-heated hotspots like carbon deposits or spark plug tips igniting the charge early", "High voltage discharges crossing the plug electrodes before the contact breaker opens", "Extremely high viscosity indices of the engine oil pool inside the lower pan sump", "Delays introduced by the electronic control unit during the injection duration phase"], optionsMarathi: ["काजळीमुळे इंजिनमधील गरम भाग इंधन स्पार्क मिळण्यापूर्वीच पेटवतात", "व्होल्टेजमुळे", "ऑईलमुळे", "ECU मुळे"], answer: "A", explanation: "Carbon deposits inside the cylinder can glow red-hot, acting like an unwanted spark plug that ignites the fuel prematurely.", explanationMarathi: "सिलेंडरमधील काजळी गरम होऊन ठिणगीसारखी काम करते आणि पेट्रोल स्पार्क प्लगच्या आधीच पेटवते." },
  { id: 453, chapterId: 17, question: "The component that links the valve lifter or tappet to the rocker arm in an overhead valve (OHV) arrangement is the—", questionMarathi: "OHV इंजिनमध्ये व्हॉल्व्ह लिफ्टर आणि रॉकर आर्म यांना कोण जोडते?", options: ["Push rod assembly", "Connecting rod beam", "Gudgeon pin shaft", "Camshaft gear teeth"], optionsMarathi: ["पुश रॉड (Push rod)", "कनेक्टिंग रॉड", "गजन पिन", "कॅमशाफ्ट गिअर"], answer: "A", explanation: "The push rod transfers the lifting movement of the camshaft tappet up to the rocker arm, which then opens the valve.", explanationMarathi: "कॅमशाफ्टच्या हालचालीला पुश रॉड वर घेऊन रॉकर आर्मला देतो, जो व्हॉल्व्ह उघडतो." },
  { id: 454, chapterId: 17, question: "The water jackets of an internal combustion engine cylinder block are designed to—", questionMarathi: "इंजिन ब्लॉकच्या 'वॉटर जॅकेट्स'चे काम काय?", options: ["Provide channels for cooling liquid to circulate directly around the hot cylinder walls", "Store an auxiliary reservoir supply of lubricating oil for the main bearings", "Trap unburnt exhaust gas vapors for recirculation to the intake system", "Reduce the overall mechanical weight of the reciprocating piston structure"], optionsMarathi: ["सिलेंडरच्या भिंतींभोवती कुलंट फिरवून इंजिन थंड ठेवणे", "ऑईल साठवणे", "धूर अडवणे", "वजन कमी करणे"], answer: "A", explanation: "These jackets are passages that allow coolant to flow around the combustion chamber, absorbing the intense heat generated during combustion.", explanationMarathi: "सिलेंडरच्या गरम भिंतींभोवती पाणी फिरवून उष्णता काढून घेण्यासाठी ही जॅकेट्स बनवलेली असतात." },
  { id: 455, chapterId: 17, question: "In a full-pressure lubricating system, oil is delivered to the connecting rod big-end bearings via—", questionMarathi: "इंजिनमध्ये कनेक्टिंग रॉडच्या बेअरिंगला तेल कसे पोहोचते?", options: ["Internal oil holes kiva drillings executed through the crankshaft journals", "Splashing action generated by the dipper caps attached to the crankcase", "Small electronic injection nozzles spraying mist from the cylinder liner base", "Direct gravitational overflow channels from the overhead camshaft oil gallery"], optionsMarathi: ["क्रँकशाफ्टमध्ये ड्रिल केलेल्या छिद्रांमधून", "स्प्लॅशिंग (Splash) पद्धतीने", "स्प्रे पद्धतीने", "गुरुत्वाकर्षणाने"], answer: "A", explanation: "The oil pump pushes oil into the crankshaft, and internal holes lead this oil directly to the main bearings and connecting rod bearings.", explanationMarathi: "ऑईल पंप तेल क्रँकशाफ्टच्या आतल्या बारीक नळ्यांमध्ये पाठवतो, तिथून ते थेट बेअरिंगपर्यंत पोहोचते." },
  { id: 456, chapterId: 17, question: "The main advantage of a Multi-Point Fuel Injection (MPFI) petrol system over a conventional carburetor layout is—", questionMarathi: "MPFI सिस्टीमचा फायदा काय?", options: ["Precise and equal air-fuel distribution to each individual cylinder for better efficiency", "Complete simplification of the electrical loop by eliminating sensors and ECU maps", "Capability to run safely on high viscosity diesel or bio-fuel blends in emergencies", "Total reduction in the initial manufacturing cost of the intake manifold structure"], optionsMarathi: ["प्रत्येक सिलेंडरला अचूक आणि समान इंधन मिळून कार्यक्षमता वाढते", "सिस्टीम सोपी होते", "डिझेलवर चालते", "खर्च कमी होतो"], answer: "A", explanation: "MPFI sprays fuel directly at the intake port of each cylinder, ensuring each cylinder receives the exact correct amount of fuel.", explanationMarathi: "कार्ब्युरेटरपेक्षा MPFI मध्ये प्रत्येक सिलेंडरला स्वतंत्रपणे योग्य तितके इंधन मिळते, ज्यामुळे मायलेज आणि पॉवर दोन्ही वाढतात." },
  { id: 457, chapterId: 17, question: "In a modern common rail direct injection (CRDI) diesel setup, the fuel pressure is regulated by an electronic sensor and a—", questionMarathi: "CRDI इंजिनमध्ये डिझेलचा दाब कशाने नियंत्रित केला जातो?", options: ["Pressure Control Valve (PCV) kiva fuel rail regulator", "Mechanical centrifugal governor flyweight sleeve", "Vacuum advance diaphragm module line connected to the manifold", "High capacity fuel lift pump check valve terminal"], optionsMarathi: ["प्रेशर कंट्रोल व्हॉल्व्ह (PCV) किंवा फ्युएल रेल रेग्युलेटर", "गव्हर्नर", "व्हॅक्यूम रेग्युलेटर", "लिफ्ट पंप"], answer: "A", explanation: "The PCV constantly adjusts fuel pressure based on engine load and speed, ensuring optimal injection pressure.", explanationMarathi: "फ्युएल रेलमध्ये किती दाब असावा, हे PCV (प्रेशर कंट्रोल व्हॉल्व्ह) आणि सेन्सर मिळून ठरवतात." },
  { id: 458, chapterId: 17, question: "The device that steps up low battery voltage (12V) to high voltage (10-20kV) inside a conventional ignition circuit is the—", questionMarathi: "इग्निशन सर्किटमध्ये कमी विजेचे रूपांतर जास्त विजेत (१२V ते २०kV) करणारा घटक कोणता?", options: ["Ignition coil consisting of primary and secondary winding layers", "Distributor unit contact breaker points plate assembly", "Condenser kiva capacitor wired in parallel across the breaker terminals", "Electronic spark plug gap core insulator block"], optionsMarathi: ["इग्निशन कॉईल (Ignition coil)", "डिस्ट्रिब्यूटर", "कंडेन्सर", "स्पार्क प्लग"], answer: "A", explanation: "The ignition coil's two windings turn low battery voltage into high-voltage electricity needed to jump the spark plug gap.", explanationMarathi: "कॉईलमध्ये दोन वाइंडिंग्स असतात, जी १२ व्होल्टची वीज वाढवून स्पार्क प्लगला पुरवते." },
  { id: 459, chapterId: 17, question: "Frictional power (F.P.) of an automobile engine performance test is mathematically defined as—", questionMarathi: "'फ्रिक्शनल पॉवर' (F.P.) म्हणजे काय?", options: ["Indicated Power (I.P.) minus Brake Power (B.P.)", "Brake Power (B.P.) divided by mechanical efficiency indices", "Fuel energy input multiplied by total thermal efficiency coefficients", "Swept volume capacity divided by the total clearance volume space"], optionsMarathi: ["इंडिकेटेड पॉवर (IP) वजा ब्रेक पॉवर (BP)", "BP भागाकार", "इंधनाची ताकद", "पिस्टनची हालचाल"], answer: "A", explanation: "Frictional power is the energy lost overcoming internal engine friction and driving accessories, calculated by subtracting the useful power (BP) from the power generated in the cylinder (IP).", explanationMarathi: "इंजिनमध्ये निर्माण झालेली ताकद (IP) आणि चाकापर्यंत पोहोचणारी ताकद (BP) यांच्यातील फरकाची ताकद म्हणजेच इंजिनच्या आत झालेली घर्षणाची हानी (Frictional Power) होय." },
  { id: 460, chapterId: 17, question: "A turbocharger intercooler is classified as an air-to-air or air-to-liquid—", questionMarathi: "इंटरकुलर हे काय आहे?", options: ["Heat exchanger designed to drop compressed charge temperatures and boost density", "Filtration matrix to stop microscopic soot particles entering the block ports", "Accumulator vessel storing high pressure vapors for cold starting operations", "Baffle chamber to damp out high frequency pneumatic induction noise waves"], optionsMarathi: ["उष्णता बदलणारा (Heat exchanger) घटक, जो हवा थंड करून तिचा घनता वाढवतो", "फिल्टर", "टाकी", "आवाज कमी करणारी पेटी"], answer: "A", explanation: "It exchanges heat from the hot intake air to either the atmosphere (air) or coolant (liquid) to increase air density for more power.", explanationMarathi: "इंटरकुलर गरम हवेला थंड करून तिची घनता वाढवतो, ज्यामुळे इंजिनमध्ये जास्त हवा जाते आणि जास्त ताकद मिळते." },
  { id: 461, chapterId: 17, question: "The type of clutch mechanism that utilizes centrifugal weights to increase gripping pressure as engine speed rises is the—", questionMarathi: "वेगासोबत दाबाची ताकद वाढवणारा क्लच कोणता?", options: ["Semi-centrifugal or fully automatic centrifugal clutch setup", "Conventional multi-plate manual dry friction clutch layout", "Single-plate diaphragm spring driven clutch configuration", "Hydraulic torque converter fluid flywheel assembly sleeve"], optionsMarathi: ["सेमी-सेंट्रीफ्युगल क्लच", "मॅन्युअल क्लच", "डायफ्राम क्लच", "हायड्रॉलिक टॉर्क कन्व्हर्टर"], answer: "A", explanation: "As engine speed increases, centrifugal force throws weights outward, pressing the clutch tighter to prevent slippage.", explanationMarathi: "गाडीचा वेग जसा वाढतो, तसे यातील वजन बाहेरच्या दिशेला फेकले जाते आणि क्लचचा दाब वाढतो, ज्यामुळे तो निसटत नाही (Slip होत नाही)." },
  { id: 462, chapterId: 17, question: "In a constant mesh manual transmission, the dog clutch sleeve is slid axially on the splines of the main shaft to—", questionMarathi: "कॉन्स्टंट-मेश गिअरबॉक्समध्ये डॉग क्लचचा वापर कशासाठी होतो?", options: ["Lock the selected loose gear securely to the main shaft for power transmission", "Shift the countershaft gears out of mesh with the lay shaft structure layout", "Match the input rotational speeds of the engine crankshaft face directly", "Drive the speedometer cable pinion drive line terminal instantly"], optionsMarathi: ["निवडलेला गिअर मुख्य शाफ्टला घट्ट जोडण्यासाठी", "गिअर्स वेगळे करण्यासाठी", "वेग समान करण्यासाठी", "स्पीडोमीटर फिरवण्यासाठी"], answer: "A", explanation: "The dog clutch acts as a coupler, mechanically locking the rotating gear to the output shaft.", explanationMarathi: "जेव्हा आपण गिअर बदलतो, तेव्हा डॉग क्लच फिरणाऱ्या गिअरला मुख्य शाफ्टशी लॉक करतो, ज्यामुळे ताकद पुढे जाते." },
  { id: 463, chapterId: 17, question: "The component that permits a change in the driving angle between the transmission output shaft and the propeller shaft is the—", questionMarathi: "गिअरबॉक्स आणि प्रोपेलर शाफ्टमधील कोन बदलण्यासाठी कशाचा वापर होतो?", options: ["Universal joint kiva Hooke’s joint assembly", "Slip joint splined tracking sleeve element", "Center support bearing housing rubber ring", "Oldham’s coupling slider disk block interface"], optionsMarathi: ["युनिव्हर्सल जॉइंट (Universal joint)", "स्लिप जॉइंट", "सेंटर बेअरिंग", "ओल्डहॅम कपलिंग"], answer: "A", explanation: "Universal joints allow the shaft to transfer rotational power even when the shafts are at an angle to each other.", explanationMarathi: "गाडीच्या हालचालीमुळे प्रोपेलर शाफ्टचा कोन बदलत असतो, तो कोन पेलून फिरण्याचे काम युनिव्हर्सल जॉइंट करतो." },
  { id: 464, chapterId: 17, question: "In a final drive assembly, the hypoid pinion mesh introduces a unique advantage by allowing the propeller shaft axis to be—", questionMarathi: "डिफरेंशियलमध्ये 'हायपॉइड पिनियन'चा फायदा काय?", options: ["Placed below the center line of the crown wheel axle for lower vehicle height", "Aligned at a perfect perpendicular 90-degree intersection above the main axle beam", "Eliminated completely from the vehicle chassis layout by using direct transaxles", "Driven at twice the rotational velocity parameters of the engine crankshaft"], optionsMarathi: ["प्रोपेलर शाफ्ट खाली बसवता येतो, ज्यामुळे गाडीची उंची कमी होते", "९० अंशात बसवणे", "शाफ्टची गरज नाही", "वेग वाढवणे"], answer: "A", explanation: "Hypoid gears allow the drive pinion to be offset from the center of the ring gear, which lets the transmission tunnel sit lower in the floor.", explanationMarathi: "हायपॉइड गिअर्समुळे प्रोपेलर शाफ्ट सेंटरपेक्षा थोडा खाली बसवता येतो, त्यामुळे गाडीच्या आतील मजल्यावरील बोगदा (Tunnel) कमी होतो आणि गाडीला कमी उंची मिळते." },
  { id: 465, chapterId: 17, question: "If a vehicle utilizes a full-floating rear axle configuration, if an axle shaft breaks completely under load—", questionMarathi: "फुल-फ्लोटिंग अ‍ॅक्सलचा शाफ्ट तुटल्यास काय होईल?", options: ["The wheel remains on the housing and the vehicle can be towed safely", "The wheel comes off the vehicle chassis instantly along with the hub block", "The braking system performance drops to absolute zero efficiency parameters", "The differential casing housing slips off its mounting pad seats immediately"], optionsMarathi: ["चाक जागेवर राहते आणि गाडी टो (Tow) करता येते", "चाक निखळून बाहेर पडते", "ब्रेक लागत नाही", "डिफरेंशियल खाली पडते"], answer: "A", explanation: "In a full-floating axle, the bearings support the wheel independently of the axle shaft, so the shaft only transmits torque.", explanationMarathi: "फुल-फ्लोटिंगमध्ये गाडीचे पूर्ण वजन अ‍ॅक्सल हाउसिंगवर असते. शाफ्ट फक्त चाक फिरवण्याचे काम करतो, म्हणून तो तुटला तरी चाक बाहेर येत नाही." },
  { id: 466, chapterId: 17, question: "The angle between the steering axis centerline and a true vertical line when viewed from the front of the vehicle is the—", questionMarathi: "सामोरून पाहिले असता स्टीअरिंग ॲक्सिस आणि उभ्या रेषेमधील कोनाला काय म्हणतात?", options: ["Kingpin Inclination (KPI) or Steering Axis Inclination (SAI)", "Camber angle displacement parameter index", "Caster angle forward or backward tilt setting", "Included angle sum parameter calculation index"], optionsMarathi: ["किंगपिन इन्क्लिनेशन (KPI)", "कॅम्बर अँगल", "कास्टर अँगल", "इन्क्लुडेड अँगल"], answer: "A", explanation: "This angle is called KPI or SAI and is essential for steering self-centering.", explanationMarathi: "याला किंगपिन इन्क्लिनेशन (KPI) म्हणतात. हे स्टीअरिंग स्थिर ठेवण्यास मदत करते." },
  { id: 467, chapterId: 17, question: "The steering gear box type that utilizes a small gear wheel meshing with a flat toothed tracking bar is the—", questionMarathi: "कोणत्या स्टीअरिंगमध्ये गिअर चाक एका सपाट रॅकशी जोडलेले असते?", options: ["Rack and pinion steering gear box configuration", "Recirculating ball worm and nut mechanism layout", "Worm and roller sector tracking arm block assembly", "Cam and peg steering gear system lever layout"], optionsMarathi: ["रॅक आणि पिनियन स्टीअरिंग (Rack and pinion)", "रिसर्क्युलेटिंग बॉल", "वॉर्म आणि रोलर", "कॅम आणि पेग"], answer: "A", explanation: "Rack and pinion is a direct and simple system where the steering wheel turns a pinion, which moves the rack bar side-to-side.", explanationMarathi: "यात गोल गिअर (Pinion) सरळ दाते असलेल्या पट्टीला (Rack) ढकलतो, ज्यामुळे चाके वळतात." },
  { id: 468, chapterId: 17, question: "The shackle used at one end of a semi-elliptical leaf spring suspension assembly is a—", questionMarathi: "लीफ स्प्रिंगच्या टोकाला वापरलेले 'शॅकल' काय आहे?", options: ["Flexible swinging link that allows spring length variations during deflection", "Rigid clamping block locking the leaves directly to the frame cross member", "Rubber bumper block dampening excessive high frequency vertical bounce shocks", "Pivot pin interface anchoring the master leaf eye to the front bracket base"], optionsMarathi: ["लवचिक दुवा (Swinging link) जो स्प्रिंगची लांबी बदलू देतो", "कडक क्लॅम्प", "रबर बंपर", "पििव्हट पिन"], answer: "A", explanation: "When a spring compresses, it stretches. The shackle swings to accommodate this length change.", explanationMarathi: "जेव्हा स्प्रिंग दाबली जाते, तेव्हा ती लांब होते. शॅकल ही हालचाल सामावून घेते, अन्यथा स्प्रिंग तुटू शकते." },
  { id: 469, chapterId: 17, question: "In a tandem master cylinder setup, the presence of two independent piston chambers ensures that if a leak occurs—", questionMarathi: "टँडम मास्टर सिलेंडरमध्ये दोन कप्पे का असतात?", options: ["One circuit continues to function safely to provide partial braking capability", "Both front and rear fluid pipelines block up instantly to slide the tires", "The vacuum booster servo diaphragm locks the pedal at its maximum height", "Frictional heat generation on the drum linings drops to absolute zero parameters"], optionsMarathi: ["एक सर्किट लिक झाले तरी दुसरे सर्किट गाडी सुरक्षित थांबवू शकते", "दोन्ही ब्रेक जाम होतात", "ब्रेक पॅडल जाम होतो", "उष्णता कमी होते"], answer: "A", explanation: "The tandem design provides redundancy, so a single leak won't cause complete brake failure.", explanationMarathi: "ही सुरक्षेची सोय आहे. जर एका पाइपमधून तेल गळले, तरी दुसऱ्या पाइपमुळे ब्रेक लागत राहतो आणि अपघात टळतो." },
  { id: 470, chapterId: 17, question: "The component that transfers the braking force from a disc brake pad directly to the rotating wheel hub assembly is the—", questionMarathi: "ब्रेकची ताकद चाकापर्यंत कोण पोहोचवते?", options: ["Brake disc rotor bolted directly to the wheel hub face", "Master cylinder tandem piston secondary push rod link", "Wheel cylinder expansion cup lip rubber ring sealing layout", "Brake backing plate assembly anchored onto the axle casing tube"], optionsMarathi: ["ब्रेक डिस्क (Disc rotor)", "मास्टर सिलेंडर", "व्हील सिलेंडर", "ब्रेक बॅकिंग प्लेट"], answer: "A", explanation: "The brake pads press against the rotor (disc), which is bolted to the wheel hub, thus forcing the wheel to slow down.", explanationMarathi: "ब्रेक पॅड्स डिस्कला दाबतात आणि डिस्क थेट चाकाच्या हबला जोडलेली असते, त्यामुळे चाक फिरणे थांबते." }
];

const questionsString = set15Questions.map(q => JSON.stringify(q, null, 2)).join(',\n');

// 3. Append to QUESTIONS array
const lastBracketIdx = content.lastIndexOf('];');
if (lastBracketIdx !== -1) {
    const finalContent = content.substring(0, lastBracketIdx).trimEnd();
    const separator = finalContent.endsWith(',') ? '\n' : ',\n';
    fs.writeFileSync(filePath, finalContent + separator + questionsString + '\n];', 'utf8');
    console.log("Successfully added Set 15 (Questions 441-470) as Chapter 17!");
} else {
    console.error("Could not find end of QUESTIONS array.");
}
